# DICE Curator Actions Configuration
# Defines retention policies for different log types

# ============================================================================
# LOG RETENTION ACTIONS
# ============================================================================

# Action 1: Delete old application logs (30 days retention for development)
actions:
  1:
    action: delete_indices
    description: >-
      Delete DICE application log indices older than 30 days for development environment.
      Production should retain for 180 days.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: dice-logs-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 30
      exclude:

  # Action 2: Delete old security logs (90 days retention - longer for security)
  2:
    action: delete_indices
    description: >-
      Delete DICE security log indices older than 90 days.
      Security logs are retained longer for compliance.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: dice-security-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 90
      exclude:

  # Action 3: Close old indices to save resources
  3:
    action: close
    description: >-
      Close DICE log indices older than 7 days to reduce resource usage
      while keeping them searchable.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: dice-logs-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 7
      exclude:
    - filtertype: closed
      exclude: True

  # Action 4: Optimize old indices (force merge)
  4:
    action: forcemerge
    description: >-
      Optimize DICE log indices older than 2 days by force merging to 1 segment.
    options:
      max_num_segments: 1
      ignore_empty_list: True
      timeout_override: 21600
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: dice-logs-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 2
      exclude:
    - filtertype: forcemerged
      max_num_segments: 1
      exclude: True 