# DICE Kibana Configuration
# Dashboard and visualization for distributed logging

# ============================================================================
# SERVER SETTINGS
# ============================================================================
server.name: dice-kibana
server.host: 0.0.0.0
server.port: 5601
server.basePath: ""
server.rewriteBasePath: false

# ============================================================================
# ELASTICSEARCH CONNECTION
# ============================================================================
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.preserveHost: true
elasticsearch.username: ""
elasticsearch.password: ""

# ============================================================================
# KIBANA INDEX SETTINGS
# ============================================================================
kibana.index: ".kibana-dice"
kibana.defaultAppId: "dashboard"

# ============================================================================
# LOGGING SETTINGS
# ============================================================================
logging.root.level: warn
logging.loggers:
  - name: plugins.security
    level: info
  - name: elasticsearch.deprecation
    level: warn

# ============================================================================
# MONITORING & TELEMETRY
# ============================================================================
monitoring.enabled: false
telemetry.enabled: false
telemetry.optIn: false

# ============================================================================
# DEVELOPMENT SETTINGS
# ============================================================================
status.allowAnonymous: true
server.maxPayload: 1048576

# ============================================================================
# DASHBOARD SETTINGS
# ============================================================================
map.includeElasticMapsService: false
newsfeed.enabled: false

# ============================================================================
# SECURITY SETTINGS (Development)
# ============================================================================
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "dice-logging-encryption-key-32-chars-min"

# ============================================================================
# DATA VISUALIZATION SETTINGS
# ============================================================================
data.search.aggs.shardDelay.enabled: true
data.search.sessions.enabled: false

# ============================================================================
# SAVED OBJECTS
# ============================================================================
savedObjects.maxImportPayloadBytes: 26214400

# ============================================================================
# DICE-SPECIFIC SETTINGS
# ============================================================================
# Default index patterns for DICE services
kibana.defaultIndexPattern: "dice-logs-*"

# Custom branding (optional)
server.customResponseHeaders:
  X-Content-Type-Options: "nosniff"
  X-Frame-Options: "DENY" 