# Minimal Docker Compose for DevContainer
# This file is specifically optimized for DevContainer CLI compatibility

services:
  postgres:
    image: postgres:17-bullseye
    environment:
      POSTGRES_DB: dice_db
      POSTGRES_USER: dice_user
      POSTGRES_PASSWORD: dice_dev_password_default
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-bullseye
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../workspace/backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dice_user:dice_dev_password_default@postgres:5432/dice_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dice_jwt_secret_development_default
      - PORT=3001
    volumes:
      - ../workspace/backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - "3001:3001"
      - "9229:9229"
    depends_on:
      - postgres
      - redis

  pwa:
    build:
      context: ../workspace/pwa
    environment:
      - NODE_ENV=development
      - ASTRO_TELEMETRY_DISABLED=1
    volumes:
      - ../workspace/pwa:/app
      - pwa_node_modules:/app/node_modules
    ports:
      - "3000:3000"

  localstack:
    image: localstack/localstack:4.0
    environment:
      - SERVICES=s3,dynamodb,kinesis
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566:4566"

volumes:
  postgres_data:
  backend_node_modules:
  pwa_node_modules: 